fixtures:
  repositories:
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    postgresql: "https://github.com/puppetlabs/puppet-postgresql.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    ruby: "https://github.com/puppetlabs/puppetlabs-ruby.git"
    pe_gem: "https://github.com/puppetlabs/puppetlabs-pe_gem.git"
    systemd: "https://github.com/camptocamp/puppet-systemd.git"
  symlinks:
    zabbix: "#{source_dir}"
